#!/bin/bash

# Compare two files with diff and format the output
file=$1
if [ -z "$1" ]; then
    option="-y"
else
    option=$2
fi

colordiff $option io/$file expected/$file > file.txt

# Lines starting with '+'
grep '^+' file.txt > plus_lines.txt

# Lines starting with '-'
grep '^-' file.txt > minus_lines.txt

# Combine into two columns
paste plus_lines.txt minus_lines.txt > file.diff

#!/bin/bash

# Define ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
# Read the input file line by line
while IFS= read -r line
do
    # Check the first character of the line
    first_char="${line:0:1}"
    if [[ "$first_char" == "+" ]]
    then
        # If the line starts with '+', print it in green in the first column
        printf "${GREEN}%-40s${NC}" "$line"
    elif [[ "$first_char" == "-" ]]
    then
        # If the line starts with '-', print it in red in the second column
        printf "%-3s ${RED}%-40s${NC}\n" "$$$" "$line"
    else
        # Otherwise, print the line in yellow
        printf "${YELLOW}%-40s %-40s${NC}\n" "$line" ""
    fi
done < "file.diff"
echo ""


# cat two_columns.txt
